### ISSUE TITLE
Fix fallback string if only labels in meta fields are provided

### ISSUE THREAD

**Issue by pythoninja** [pythoninja/sshgen#1]
hosts:

```yaml
group1: # host_group
  hosts:
    host1: # host
      ansible_host: 127.0.0.1
      ansible_user: root

    host2:
      ansible_host: 127.0.0.2
      ansible_user: manager
      ansible_password:
      _meta:
        _aliases: [ "alias1" ]

```

Output:

```
Host host1  # group1
    HostName 127.0.0.1
    User root
    IdentityFile ~/.ssh/ssh_key
    IdentitiesOnly yes

Host host2 alias1 # group1
    HostName 127.0.0.2
    User manager
    None None
```

Expected as:

```
Host host1  # group1
    HostName 127.0.0.1
    User root
    IdentityFile ~/.ssh/ssh_key
    IdentitiesOnly yes

Host host2 alias1 # group1
    HostName 127.0.0.2
    User manager
    IdentityFile ~/.ssh/ssh_key
    IdentitiesOnly yes
```
