### ISSUE TITLE
Warn if alias duplicate found in host

### ISSUE THREAD

**Issue by pythoninja** [pythoninja/sshgen#157]
Host example:

```yaml
group2:
  hosts:
    host3:
      ansible_host: 172.19.0.1
      ansible_user: postgres
      ansible_password:
      ansible_port: 19222

    host4:
        ansible_host: 172.99.99.99
        ansible_user: 'host4-user'
        _meta:
          _auth_type: IdentityAgent
          _auth_path: ~/.1password/agent.sock
          _aliases: [ "postgres-server", "postgres-server", "host-4" ]
          _skip: false
```

The string `_aliases: [ "postgres-server", "postgres-server", "host-4" ]` contains duplicate values. App should expose a warning in this case.
