### ISSUE TITLE
Exclude host with specified meta information

### ISSUE THREAD

**Issue by pythoninja** [pythoninja/sshgen#16]
```yaml
group1: # host_group
  hosts:
    host1: # host
      ansible_host: 127.0.0.1
      ansible_user: root
      _meta:
        _auth_type: IdentityAgent
        _auth_path: ~/.1password/agent.sock
        _aliases: [ "base", "another-alias" ]
        _skip: true  # this host will be skipped from the final file
```
