### ISSUE TITLE
Do not add whitespace if no aliases are defined

### ISSUE THREAD

**Issue by pythoninja** [pythoninja/sshgen#173]
Consider this YAML example:

```yaml
group2:
  hosts:
    host5:
      ansible_host: 172.19.19.19
      ansible_user: 'host5-user'
      _meta:
        _aliases: [ "host5" ]

    host3:
      ansible_host: 172.19.0.1
      ansible_user: postgres
      ansible_password:
      ansible_port: 19222
```

Currently, processing it will show the next result:

```
Host host5  # group2
    HostName 172.19.19.19
    User host5-user
    Port 22
    IdentityFile ~/.ssh/ssh_key
    IdentitiesOnly yes

Host host3  # group2
    HostName 172.19.0.1
    User postgres
    Port 19222
    IdentityFile ~/.ssh/ssh_key
    IdentitiesOnly yes
```

I want to remove additional whitespace after hostname and before `#`.
