### ISSUE TITLE
Trim whitespaces in strings before write'em

### ISSUE THREAD

**Issue by pythoninja** [pythoninja/sshgen#174]
Consider this YAML example:

```yaml
group1: # host_group
  hosts:
    host1: # host
      ansible_host: 127.0.0.1
      ansible_user: root
      _meta:
        _auth_type: IdentityAgent
        _auth_path: ~/.1password/agent.sock
        _aliases: [ "base", "another-alias          " ]
        _skip: false
```

The result after processing would be like this:

```
Host host1 base another-alias           # group1
    HostName 127.0.0.1
    User root
    Port 22
    IdentityAgent ~/.1password/agent.sock
```

All whitespace chars should be trimmed before saving to the final file.
