### ISSUE TITLE
Add support for custom SSH port

### ISSUE THREAD

**Issue by pythoninja** [pythoninja/sshgen#49]
Consider this hosts.yml:

```yaml

group1: # host_group
  hosts:
    host1: # host
      ansible_host: 127.0.0.1
      ansible_user: root
      ansible_port: 2322
      _meta:
        _auth_type: IdentityAgent
        _auth_path: ~/.1password/agent.sock
        _aliases: [ "base", "another-alias" ]
        _skip: false

```

Produce following ssh configuration file:

```
Host host1 base another-alias # group1
    HostName 127.0.0.1
    User root
    Port 2322
    IdentityAgent ~/.1password/agent.sock
```
